### ISSUE TITLE
How to pass to adminlte.php the id of the logged in user?

### ISSUE THREAD

**Issue by ronaldaraujo** [jeroennoten/Laravel-AdminLTE#185]
How to pass to adminlte.php the id of the logged in user?

I tried to do the basics that would be:

```
'menu' => [
        ...
        'PROFILE',
        [
            'text' => 'Perfil',
            'url'  => 'admin/profiles/'.Auth::user()->id.'/edit',
            'icon' => 'user',
        ],
        ...
```

But I get an error.

`Fatal error: Uncaught ReflectionException: Class view does not exist in /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Container/Container.php:752 Stack trace: #0 /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view') #1 /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('view') #2 /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('view', Array) #3 /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('view', Array) #4 /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\Foundation\Application->make('view', Array) #5 /home/ronal in /home/ronaldaraujo/workspace/nivelgas/web2/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752`

**Comment by ronaldaraujo** [comment]
I found a solution in: https://stackoverflow.com/questions/46268586/laravel-adminlte-php-doesnt-recognize-authid
