### ISSUE TITLE
Unable to locate a class or view for component [adminlte-button]. (For all components)

### ISSUE THREAD

**Issue by Rodrigo-Weich** [jeroennoten/Laravel-AdminLTE#756]
Hi, I have the following problem: Unable to locate a class or view for component [adminlte-button], for all the components, I already tried to change the version of laravel and even then the problem persists, I believe I am doing something wrong, Can someone help me? I already thank and apologize for my English as a tutor.

**Comment by Shidersz** [comment]
What project version are you using? The components are still on development stage (on a particular branch), there is no way you can see that error if you are using the latest release and not using any [component](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/12.-Blade-X-Components-(Incoming)).

**Comment by Rodrigo-Weich** [comment]
I believe that's it

Laravel 8 version (tested with 7 and 6 too)
AdminLTE version 3.0.5

**Comment by Shidersz** [comment]
@Rodrigo-Weich You will have to wait, they will be available on next releases. I'm working all I can on my free time to get they done.

**Comment by Rodrigo-Weich** [comment]
No problem, I understand that it is very busy, can you tell me which is the latest version that works? I would like to go playing and testing until the next versions come out :)

**Comment by Shidersz** [comment]
The latest release of this package is [v3.5.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.5.0) but it don't include any component. Maybe you can use the development branch [add-x-components](https://github.com/jeroennoten/Laravel-AdminLTE/tree/add-x-components) on the composer require command, but I'm not sure which would be the syntax for that. Next post may help:

https://stackoverflow.com/questions/33525885/composer-require-branch-name

**Comment by joaobonanca** [comment]
Hey, so how are we suppost to use plugins?

**Comment by Shidersz** [comment]
Hi @joaobonanca , are you using the `add-x-component` branch right? On the other hand the `active => true` will make the plugin files available on all the pages, so there is no need to use `@section('plugins.bootstrapSwitch', true)` in that case. Also, as explained [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/12.-Blade-X-Components-(On-Development-Stage---Incoming-On-New-Releases)#inputswitch), only `js` file is required for this plugin. As an example, I will show you my current setup:

On the **plugins** configuration of `adminlte.php` file:
```php
'BootstrapSwitch' => [
    'active' => false,
    'files' => [
        [
            'type' => 'js',
            'asset' => true,
            'location' => 'vendor/bootstrap-switch/js/bootstrap-switch.min.js',
        ],
    ],
],
```
On the page where I want to use the plugin I have this:
```php
@section('plugins.BootstrapSwitch', true)
```
Also, you may check access permissions on the `vendor/bootstrap-switch` folder if problem persists (always inspect the browser console to check for any errors...).

Any feedback about the components is welcome, same to you @Rodrigo-Weich .

**Comment by joaobonanca** [comment]
Hi @Shidersz and thank you for such a brief response.
I have deleted the css part and active is false now.
The file permissions are this:
![image](https://user-images.githubusercontent.com/45144277/98471300-2cedb200-21e3-11eb-89c6-aa0908d7c3ed.png)

**Comment by Shidersz** [comment]
Ok, lets go step by step...

**1)** Component are under development, they will be only available if you use the `add-x-components` branch, I believe you can do that with `composer require jeroennoten/laravel-adminlte:dev-add-x-components` (but I have not tested that). ARE YOU USING THIS BRANCH?

**2)** Are you using **Laravel Mix**? In that case I'm not sure how the plugins should be included (see workaround). I suspect this because you have a file named `mix-manifest.json`.

**3)** Check the browser's console development tool to see what errors do you see.

### If you are using Laravel Mix you can try next workaround:

**A)** Locate the `master.blade.php` file. If you have published the main views, it should be on `resources/views/vendor/adminlte/master.blade.php`, otherwise it should be on `vendor/jeroennoten/laravel-adminlte/resources/views/master.blade.php`.

**B)** Make next changes on the file:

Change:

```blade
{{-- Base Stylesheets --}}
@if(!config('adminlte.enabled_laravel_mix'))
    <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">

    {{-- Configured Stylesheets --}}
    @include('adminlte::plugins', ['type' => 'css'])

    <link rel="stylesheet" href="{{ asset('vendor/adminlte/dist/css/adminlte.min.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
@else
    <link rel="stylesheet" href="{{ mix(config('adminlte.laravel_mix_css_path', 'css/app.css')) }}">
@endif
```
by next code on the head definition

```blade
{{-- Base Stylesheets --}}
@if(!config('adminlte.enabled_laravel_mix'))
    <link rel="stylesheet" href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/overlayScrollbars/css/OverlayScrollbars.min.css') }}">

    {{-- Configured Stylesheets --}}
    @include('adminlte::plugins', ['type' => 'css'])

    <link rel="stylesheet" href="{{ asset('vendor/adminlte/dist/css/adminlte.min.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
@else
    <link rel="stylesheet" href="{{ mix(config('adminlte.laravel_mix_css_path', 'css/app.css')) }}">
    {{-- Workaround to Add Configured Stylesheets --}}
    @include('adminlte::plugins', ['type' => 'css'])
@endif
```

Also, do similar change on the body, it should be like this:

```blade
{{-- Base Scripts --}}
@if(!config('adminlte.enabled_laravel_mix'))
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>

    {{-- Configured Scripts --}}
    @include('adminlte::plugins', ['type' => 'js'])

    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
@else
    <script src="{{ mix(config('adminlte.laravel_mix_js_path', 'js/app.js')) }}"></script>
    {{-- Workaround to Add Configured Scripts --}}
    @include('adminlte::plugins', ['type' => 'js'])
@endif
```

However, you should find the **NICE** way to include the plugins when using Laravel Mix

**Comment by joaobonanca** [comment]
Ohh ok i misread.
1. I duplicated my project and tried. Works perfectly. Just for future readers, make sure to load the plugin after jquery because i got that error.
2. I am not using mix. Should i?
Im not using it because the config/adminlte.php manages it all in one place.
3. With the branch i was using and the way i did it, got 0 errors.
Thank you for your amazing job and assistance.

**Comment by Shidersz** [comment]
> 
> 
> Ohh ok i misread.
> 
>     1. I duplicated my project and tried. Works perfectly. Just for future readers, make sure to load the plugin after jquery because i got that error.
> 
>     2. I am not using mix. Should i?
>        Im not using it because the config/adminlte.php manages it all in one place.
> 
>     3. With the branch i was using and the way i did it, got 0 errors.
>        Thank you for your amazing job and assistance.

I have never experimented with **Mix**, so I don't know the benefits you can get from it. However, after looking the `master.blade.php` I see that the plugins from the configuration are not included if you enable **Mix**. So, I assume it manages `css` and `js` in a different way.

On the other hand, you are welcome! Please, consider giving any feedback while testing the components...

**Comment by joaobonanca** [comment]
I will use the config file since its really well implemented.
I´ve used some of the x-blade components and so far so good.
Thank you for this wonderfull piece of engineering!

**Comment by resslinger** [comment]
Closed. The feature will come soon.

**Comment by kingIZZZY** [comment]
+1 Not working for me, on latest required version, and there's no `add-x-components` branch anymore

```
Facade\Ignition\Exceptions\ViewException: Unable to locate a class or view for component [adminlte-input-file]. (View: /redacted/myproject/resources/views/shared/custom-view.blade.php) in file /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php on line 275

#0 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(211): Illuminate\View\Compilers\ComponentTagCompiler-&gt;componentClass()
#1 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(144): Illuminate\View\Compilers\ComponentTagCompiler-&gt;componentString()
#2 [internal function]: Illuminate\View\Compilers\ComponentTagCompiler-&gt;Illuminate\View\Compilers\{closure}()
#3 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(139): preg_replace_callback()
#4 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(90): Illuminate\View\Compilers\ComponentTagCompiler-&gt;compileOpeningTags()
#5 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(76): Illuminate\View\Compilers\ComponentTagCompiler-&gt;compileTags()
#6 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(332): Illuminate\View\Compilers\ComponentTagCompiler-&gt;compile()
#7 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(229): Illuminate\View\Compilers\BladeCompiler-&gt;compileComponentTags()
#8 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(150): Illuminate\View\Compilers\BladeCompiler-&gt;compileString()
#9 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\View\Compilers\BladeCompiler-&gt;compile()
#10 /redacted/myproject/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine-&gt;get()
#11 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\Ignition\Views\Engines\CompilerEngine-&gt;get()
#12 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View-&gt;getContents()
#13 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View-&gt;renderContents()
#14 /redacted/myproject/resources/views/import.blade.php(10): Illuminate\View\View-&gt;render()
#15 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
#16 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#17 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem-&gt;getRequire()
#18 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine-&gt;evaluatePath()
#19 /redacted/myproject/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine-&gt;get()
#20 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\Ignition\Views\Engines\CompilerEngine-&gt;get()
#21 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View-&gt;getContents()
#22 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View-&gt;renderContents()
#23 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\View\View-&gt;render()
#24 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\Http\Response-&gt;setContent()
#25 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(783): Illuminate\Http\Response-&gt;__construct()
#26 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(753): Illuminate\Routing\Router::toResponse()
#27 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Router-&gt;prepareResponse()
#28 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#29 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#30 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle()
#31 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#32 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate-&gt;handle()
#33 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#34 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle()
#35 /redacted/myproject/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#36 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle()
#37 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#38 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest()
#39 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession-&gt;handle()
#40 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#41 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle()
#42 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#43 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle()
#44 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#45 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Pipeline\Pipeline-&gt;then()
#46 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#47 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router-&gt;runRoute()
#48 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router-&gt;dispatchToRoute()
#49 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router-&gt;dispatch()
#50 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#51 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#52 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#53 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#54 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#55 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#56 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#57 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#58 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#59 /redacted/myproject/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#60 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle()
#61 /redacted/myproject/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#62 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle()
#63 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#64 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline-&gt;then()
#65 /redacted/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#66 /redacted/myproject/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#67 /redacted/myproject/server.php(21): require_once('...')
#68 {main}
```

**Comment by REJack** [comment]
This looks like you not copied the vendor resource files to your app resource folder.

**Comment by kingIZZZY** [comment]
Ah, how/when is that usually supposed to happen? am i supposed to run some deploy or compile or build command which usually does this?

**Comment by kingIZZZY** [comment]
Or are blade x components altogether not available?
https://github.com/jeroennoten/Laravel-AdminLTE/issues/550#issuecomment-773301418

**Comment by REJack** [comment]
Oh yeah they are not available right now.

**Comment by humam60** [comment]
till now they didn't add it to laravel 8 !!!

**Comment by Shidersz** [comment]
@humam60 you can use `dev-master` branch to test/play the components. The issue #866 explains how you can include they in your project while we work to deliver the first version. For the moment, they are under test by some users and we are waiting for feedback to enhance some components. Why? Because once we launch the first version, it will be hard to change they interface without affecting a lot of users. So please, be patient...
