### ISSUE TITLE
[BUG] ERROR in ./vendor/almasaeed2010/adminlte/dist/js/adminlte.js

### ISSUE THREAD

**Issue by hrace009** [jeroennoten/Laravel-AdminLTE#882]
### Describe the bug
I follow this [step](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration)
And got error when run ``npm run prod``

### Steps To Reproduce
1. Open ``bootstrap.js``
2. Add `require('overlayscrollbars');` and `require('../../vendor/almasaeed2010/adminlte/dist/js/adminlte');` after `window.$ = window.jQuery = require('jquery');`
3. run `npm run prod`

### ERROR
```
ERROR in ./vendor/almasaeed2010/adminlte/dist/js/adminlte.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-external-helpers'
Require stack:
- /home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/files/plugins.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/files/index.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/index.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/src/FileCollection.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/src/components/Combine.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/src/components/ComponentRegistrar.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/src/Mix.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/laravel-mix/setup/webpack.config.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/webpack-cli/lib/webpack-cli.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/webpack-cli/lib/bootstrap.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/webpack-cli/bin/cli.js
- /home/hrace009/PhpstormProjects/goflash/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at resolve (/home/hrace009/PhpstormProjects/goflash/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at resolveStandardizedName (/home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/files/plugins.js:96:7)
    at resolvePlugin (/home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/files/plugins.js:40:10)
    at loadPlugin (/home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/files/plugins.js:48:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/config-descriptors.js:179:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/hrace009/PhpstormProjects/goflash/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/hrace009/PhpstormProjects/goflash/node_modules/gensync/index.js:291:5)
    at /home/hrace009/PhpstormProjects/goflash/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/hrace009/PhpstormProjects/goflash/node_modules/gensync/index.js:43:15)
    at Function.all (/home/hrace009/PhpstormProjects/goflash/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/home/hrace009/PhpstormProjects/goflash/node_modules/@babel/core/lib/config/config-descriptors.js:134:38)

webpack compiled with 1 error and 2 warnings
```

### Environment

| Item    | Version
| ------- | -------
| Laravel | 8.40
| Project | 3.5.4
| OS      | linux

**Comment by hrace009** [comment]
Done, solve by run this command
`npm install --save-dev @babel/plugin-external-helpers`
